calicoBackend: vxlan

ipPool:
  cidr: 172.31.0.0/16
  encapsulation: VXLAN
  natOutgoing: Enabled
  nodeSelector: all()

typha:
  enabled: false

bgp:
  enabled: false

autoDetectionMethod: "interface=eth0"

prometheus:
  enabled: false